title: notes
description: Files and other notes gathered by Alexander Tin while reporting for CBS News.
author: "Alexander Tin"
email: TinA@CBSNews.com

theme: minima

plugins:
  - jekyll-seo-tag

# Minima social links
github_username: tinalexander

# Minima custom header links
header_pages:
  - README.md

