title: notes
description: Files and other notes gathered by Alexander Tin while reporting for CBS News.
author: "Alexander Tin"
email: TinA@CBSNews.com

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Minima social links
github_username: tinalexander


