title: Alexander Tin
email: "TinA@CBSNews.com"

description: >
  This repository contains files and other notes gathered by Alexander Tin.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  social_links:
   - { platform: github,         user_url: "https://github.com/tinalexander" }

header_pages:
  - README.md
