title: notes
author:
  name: Alexander Tin
  email: TinA@CBSNews.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

description: >
  This repository contains files and other notes I gathered while covering the Biden administration’s public health agencies, including their response to infectious disease outbreaks like COVID-19 or mpox.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: github,         user_url: "https://github.com/tinalexander" }

header_pages:
  - README.md
