email: TinA@CBSNews.com

description: >
  Files and other notes gathered by Alexander Tin while reporting for CBS News.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Generate social links in footer.
  #
  # social_links:
  #   - { platform: github,         user_url: "https://github.com/tinalexander" }

header_pages:
  - README.md
