title: notes
description: Notes gathered by Alexander Tin while reporting for CBS News.
author: "Alexander Tin"
email: TinA@CBSNews.com
github_username: tinalexander

url: "https://tinalexander.github.io/notes"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
